apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: tk
type: Opaque
data:
  FLASK_SECRET_KEY: "MTJhYmNkZWYxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg=" # 생성된 실제 base64 값
  MYSQL_PASSWORD: "MmxiZU1jRTQ3Rgo=" #  base64로 인코딩
  REDIS_PASSWORD: "R2pBMFBIeDk2Tgo=" #  base64로 인코딩
  KAFKA_PASSWORD: ""
