architecture: standalone
auth:
  enabled: true
  rootPassword: "rootpassword"
  database: "my_database"
  username: "testuser"
  password: "testpass"

primary:
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

service:
  type: ClusterIP
  primary:
    port: 3306

nameOverride: "tk-mariadb"
fullnameOverride: "tk-mariadb"
