global:
  kafka:
    enabled: true
    auth:
      clientProtocol: plaintext
      interBrokerProtocol: plaintext
      sasl:
        enabled: false
      tls:
        enabled: false

kafka:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
  listeners:
    client:
      name: client
      port: 9092
      protocol: PLAINTEXT
    controller:
      name: controller
      port: 9093
      protocol: PLAINTEXT
  deleteTopicEnable: true
  autoCreateTopicsEnable: true

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 128Mi
      cpu: 50m

nameOverride: "my-kafka"
fullnameOverride: "my-kafka"
